credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "JFrog Access Token Admin Permissions"
          id: "a7119266-af16-43d2-a86a-d3ed204a7a50"
          scope: SYSTEM
          secret: "{AQAAABAAAALgCIh01dwlr79+JEvy9Qyw2azUts+8Ibz+DmhQCCEcWJ76hnBtdhLfpzbSRo/OZhKWT7KbWflhNJd8aKD2FvHSRYWjTkRIPjed/5XqJ3eMF2Puw0O65IDFBRAChoZHttsk3LoBQnjMQM4LN0v1lL3DCePzGoAwVYXOXHm/SfknwoXdOGoGRJj+yBr2UowLdc5PVggFLN5gj1BQPls0h1ZD8Y9Q6loLOoH9GqWA9vGTrAVi6UPJOuCNi72tNeFIbZEwT4W4u1dqbC2SyGQ9R8utZz32QLDtbavawPo/qMZ5a+rbNcZSky7cY7VGv/gDDkv9Y/fzWTCvpTWhcOVLfTBi/mFINHduWDaZsqaYq7Go2/OUJfB+Lr258aXygX9S0buWtrl/aMZtiS0ZeThN7jOgc+fB/nfOrRHB/BqKPh1duKCPEMSizbiPy8RDfBMIfjaRIuV6r2wjBSnytgYvnnSgvPcWN3UaJnMhYRgZZ8ys22xB03jVk+R8+/BbhsM7p35h3R/Xt3QsdGS5v6RhzQ3DELVZU0jrXLyV7HXmUu4nK18eNdnkmfRFnD42AAj88J1XRi/GCKXxWGdA28I6uh84YEadnCotC/VXt6w+Nhmy+Y/CaKJRW6jBBZMO5IkwdLDQB7Dn5cSmeqrY9pZxIhArgT3Km1GyddgrPxCJLFEE3ObRC329NnjdVgYE3LGotqt57lrfAhCCtnGlCQxnSaBFvbbdbK+n0wtnX6FlnDXwm41YIl5wMeUAKxXkNbuygH/EdLV6fX6+otDatVx2Wc3yEJ4oDYA5AoCngizmSEw24kf4jX8HwAB1VkpkF+PmP4MZAAI0nzwf/TF2F8TXGIi6FGm0Ntle6BqQgZaTAeQdOv01TDxiF1CMBw/E+yaC6DCp0P4x2Vt/jj0Yrygw78uzq+q9PsciEWzxxz7GI7oTCFij0qiIlIL8MRnvfxbumeKzFHm52CdylZ6zJk2ltfp1wnWOdmLdYEj7zBv1nUZBGEI=}"
      domain:
        description: "my local domain credentials"
        name: "Local Credentials"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  globalNodeProperties:
  - diskSpaceMonitor:
      freeDiskSpaceThreshold: "1GiB"
      freeDiskSpaceWarningThreshold: "2GiB"
      freeTempSpaceThreshold: "1GiB"
      freeTempSpaceWarningThreshold: "2GiB"
  labelAtoms:
  - name: "Lenovo-Windows-Node"
  - name: "built-in"
  - name: "docker"
  - name: "windows"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  nodes:
  - permanent:
      labelString: "windows docker"
      launcher:
        inbound:
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      name: "Lenovo-Windows-Node"
      nodeProperties:
      - diskSpaceMonitor:
          freeDiskSpaceThreshold: "1GiB"
          freeDiskSpaceWarningThreshold: "2GiB"
          freeTempSpaceThreshold: "1GiB"
          freeTempSpaceWarningThreshold: "2GiB"
      remoteFS: "C:\\repository\\Jenkin-node"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      description: "Jenkins Testing System"
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "mjhfvi"
        name: "Tzahi Cohen"
        properties:
        - "consoleUrlProvider"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "theme"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "mjhfvi@gmail.com"
        - "apiToken"
        - favoriting:
            autofavoriteEnabled: true
        - "favorite"
  slaveAgentPort: 50000
  systemMessage: "Welcome Back !!!"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      description: "Jenkins Testing System"
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: OKAIDIA
  themeManager:
    disableUserThemes: false
    theme: "dark"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  sSHD:
    port: -1
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
  artifactoryBuilder:
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQWZf5NMnWIPcPSwyo7gJ43CGxSRJQkTVg/DAYVwgFlwc=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: false
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildMonitorView:
    permissionToCollectAnonymousUsageStatistics: true
  buildStepOperation:
    enabled: false
  cacheConfig:
    cacheGetJobs: false
    cacheGetJobsMinutes: 0
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwritable: false
  groovy:
    installations:
    - name: "Groovy"
      properties:
      - installSource:
          installers:
          - groovyInstaller:
              id: "4.0.9"
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  jFrogPlatformBuilder:
    allowHttpConnections: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "mjhfvi@gmail.com"
    url: "http://localhost:8080/"
  logFileFilterConfig:
    enabledDefaultRegexp: false
    enabledDefaultRegexpAWS: false
    enabledDefaultRegexpDD: false
    enabledGlobally: false
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pluginImpl:
    enableCredentialsFromNode: false
  pollSCM:
    pollingThreadCount: 10
  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  separator:
    globalSectionHeaderStyle: "font-weight: bold;"
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  warningsParsers:
    consoleLogScanningPermitted: false
  whitelist:
    enabled: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  go:
    installations:
    - name: "GOLANG"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.21.6"
  groovy:
    installations:
    - name: "Groovy"
      properties:
      - installSource:
          installers:
          - groovyInstaller:
              id: "4.0.9"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  powerShellInstallation:
    installations:
    - home: "powershell.exe"
      name: "DefaultWindows"
    - home: "pwsh"
      name: "DefaultLinux"
